name: Rust Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install libegl-dev libfontconfig-dev libfreetype-dev libgl-dev libgles-dev libwayland-dev
    
    - name: Run tests
      run: cargo test --release --verbose
